### ISSUE TITLE
Importing into Unity2021.3.22f1 causes Compiler Errors: Namespace Netwonsoft could not be found

### ISSUE THREAD

**Issue by zongo811** [LootLocker/unity-sdk#121]
I just upgraded to Unity 2021.3.9f1 to 2021.3.22f1 and had suddenly a lot of compile errors in LootLocker. The same happened when importing LootLocker from the Asset Store into my project:

![grafik](https://user-images.githubusercontent.com/77285389/230799112-bdceb541-eefc-472e-b2db-f48ad5d3f35e.png)

It seems the Newtonsoft-Library is no longer available in Unity, it should be supplied with your project.

To reproduce:
1. Create a new project in Unity 2021.3.22f1.
2. Import LootLocker from the Asset Store

Can you give me a workaround?

**Comment by zongo811** [comment]
Found a workaround. Unity 2021.3.22f1 does not provide "Newtonsoft" anymore, in contrast to lower versions.
To install it manually, in Visual Studio use "Extras > NuGet-Paket-Manager".
Look for "Newtonsoft.Json" and install a fitting version (for me it's currently 13.0.3).
This will create a folder named "Package" in your project.
From "<Your Project>\Packages\Newtonsoft.Json.13.0.3\lib\netstandard2.0" copy "Newtonsoft.Json.dll" and "Newtonsoft.Json.xml" to your Assets-Folder. I put them into "Assets\Plugins\Newtonsoft".
Go back to Unity, which will recompile your scripts. The compile errors should be gone by now.

**Comment by kirre-bylund** [comment]
Thank you for your report, this is a known issue. A simpler workaround for you is to use the Unity package manager > Add package by name > "com.unity.nuget.newtonsoft-json" & version 3.0.2.

Regardless, this problem will be fixed in the next release of the Unity SDK. [There is a PR currently open](https://github.com/LootLocker/unity-sdk/pull/120) to switch out the dependency to Unity.Plastic.Newtonsoft.

**Comment by davidtopping02** [comment]
I am facing similar issues using Unity editor version 2021.3.21f1. These errors occur only when building. Any help would be appreciated.

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/71976336/234316516-cdf97e41-e44c-470d-8992-6c14c454d581.png">

**Comment by GiovanniBraconi** [comment]
I have the same exact problem as @davidtopping02.

**Comment by davidtopping02** [comment]
> I have the same exact problem as @davidtopping02.

hey so the workaround I used was 
-> create an externals folder in the unity package and close the  plug-in on it . so i can edit it.
-> got the version of newtonsoft package using the package manager. 
-> edited the using statements to use the newtonsoft package statements rather than the unity.newtonsoft namespace

**Comment by GiovanniBraconi** [comment]
> > I have the same exact problem as @davidtopping02.
> 
> hey so the workaround I used was -> create an externals folder in the unity package and close the plug-in on it . so i can edit it. -> got the version of newtonsoft package using the package manager. -> edited the using statements to use the newtonsoft package statements rather than the unity.newtonsoft namespace

Thanks it worked!!!

**Comment by kirre-bylund** [comment]
I just wanted to tell you all that we have just released v1.2.0 of the Unity SDK that fixes these build errors: https://github.com/LootLocker/unity-sdk/releases/tag/v1.2.0
